version: '3'

services:
    mysql-server:
        image:                   arm64v8/mysql:oracle
        hostname:                mysql-server
        environment:
            MYSQL_ROOT_PASSWORD: userpass
        volumes:
#            -                   ./db/dumps:/docker-entrypoint-initdb.d
            -                    ./db/data:/var/lib/mysql
        networks:
            -                    app-fullstack-net

    mysql-admin:
        image:                   phpmyadmin/phpmyadmin
        environment: 
            PMA_HOST:            mysql-server
            PMA_PORT:            3306
            MYSQL_ROOT_PASSWORD: userpass
        networks:
            -                    app-fullstack-net
        depends_on:
            -                    mysql-server
        ports:
            -                    "8001:80"

networks:
    app-fullstack-net:
        driver:                  bridge