version: '3'

services:
    mysql-server:
        build: ./mariaDB
        hostname: mysql-server
        environment:
          - PUID=1000
          - PGID=1000
          - MYSQL_ROOT_PASSWORD=root
          - TZ=Europe/London
          #- MYSQL_DATABASE=USER_DB_NAME #optional
          #- MYSQL_USER=MYSQL_USER #optional
          #- MYSQL_PASSWORD=DATABASE_PASSWORD #optional
          #- REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
        #volumes:
        #  - path_to_data:/config
        ports:
          - 3306:3306

#    mysql-server:
#        image:                   arm64v8/mysql:oracle
#        hostname:                mysql-server
#        environment:
#            MYSQL_ROOT_PASSWORD: userpass
#        volumes:
#            -                    ./db/dumps:/docker-entrypoint-initdb.d
#            -                    ./db/data:/var/lib/mysql
#        networks:
#            -                    app-fullstack-net
#        ports:
#            -                    "3306:3306"

    mysql-admin:
        image:                   phpmyadmin/phpmyadmin
        environment: 
            PMA_HOST:            mysql-server
            PMA_PORT:            3306
            MYSQL_ROOT_PASSWORD: userpass
        networks:
            -                    app-fullstack-net
        depends_on:
            -                    mysql-server
        ports:
            -                    "8001:80"

networks:
    app-fullstack-net:
        driver:                  bridge